## **Homework 2**

### Create a copy of the notebook to start answering the questions. Name your notebook in the format HW1_lastname_firstname.ipynb to facilitate the grading process. 

### Answer all the questions, test your code to ensure there are no errors and the results are as expected. Once you have answered all the questions, save the final copy, then go to File-> click on Download.ipynb. Once the local copy has been downloaded, submit your file on Blackboard under the corresponding assignment section. Also provide us a link to your notebook during submission. 

### **The due date of this homework is 02/12/2021 (Friday).**

### Please ensure you follow all the steps mentioned in the homework.

### All the questions have a sample input and output to help you understand the question.

### You can submit your solutions any number of times until the deadline.


**Q1. Lets consider your data is like the below cell:**

**Q1-1**: Write a program that create a dataframe from the data.

**Q1-2:** Select people that are psychologist or teacher and their number of cars is greater than their family size.

**Q1-3:** Select people who have at most 2 family members and at least 1 car.

**Q1-4:** Write a code that get number of unique jobs in this dataset.





In [ ]:
import pandas as pd

In [ ]:
data = {"name": ["Joseph", "Jacob", "Sam", "Jesee", "Ryan", "Lisa", "Lee"],
        "job": ["teacher", "psychologist", "data scientist", "software developer", "psychologist", "psychologist", "teacher"],
        "family_size": [3, 2, 1, 4, 2, 3, 2],
        "num_cars": [3, 1, 1, 2, 2, 4, 1]}

In [ ]:
# Type your solution here
# Q1 - 1 Write a program that create a dataframe from the data.
df = pd.DataFrame(data)
df.head()   # prints dataframe output in table

name                 job  family_size  num_cars
0  Joseph             teacher            3         3
1   Jacob        psychologist            2         1
2     Sam      data scientist            1         1
3   Jesee  software developer            4         2
4    Ryan        psychologist            2         2

In [ ]:
# Q1 - 2 Select people that are psychologist or teacher and their number of cars is greater than their family size.
print(df[((df.job == "psychologist") | (df.job == "teacher")) & (df.num_cars > df.family_size)])

   name           job  family_size  num_cars
5  Lisa  psychologist            3         4


In [ ]:
# Q1 - 3 Select people who have at most 2 family members and at least 1 car.
print(df[(df.family_size <= 2) & (df.num_cars >= 1)])

    name             job  family_size  num_cars
1  Jacob    psychologist            2         1
2    Sam  data scientist            1         1
4   Ryan    psychologist            2         2
6    Lee         teacher            2         1


In [ ]:
# Q1 - 4 Write a code that get number of unique jobs in this dataset.
print(df['job'].nunique()) # Prints number of unique jobs
# For fun, if you want to know the names of those unique jobs try this!
print(df['job'].unique())

4
['teacher' 'psychologist' 'data scientist' 'software developer']


**Q2. Lets consider you have two series like the below cell. Compute the mean of weights of each fruit.**

In [193]:
import numpy as np
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))

In [206]:
# Type your solution here
df1 = pd.concat([fruit, weights], axis=1)     # joins the two series
df1.groupby(fruit).mean()                     # groups by the fruit series and finds the mean for each fruit

1
apple   3.000000
banana  6.666667
carrot  5.333333

**Q3. Consider the below course_name array:**

**Q3-1**: Write a NumPy program to get the indices of the sorted elements of **course_name** array.

**Q3-2:** Write numpy code to check whether each element of **course_name** array starts with "P".


In [207]:
import numpy as np
course_name = np.array(['Python', 'JS', 'examples', 'PHP', 'html'])

In [209]:
# Type your solution here
#Q3-1
sortedIndices = np.argsort(np.char.lower(course_name)) # sort words in alphabetical order and gets indices (used lowercase letters to achieve this)
print(sortedIndices)

[2 4 1 3 0]


In [210]:
#Q3-2
checkIfStartsWithP = np.char.startswith(np.char.lower(course_name), "p")          # checks if words in array start with a p
print("Word starts with P if code says True:")
for i, j in zip(course_name, checkIfStartsWithP):                                 # prints arrays vertically next to eachother
    print(i +" :", j) 

Word starts with P if code says True:
Python : True
JS : False
examples : False
PHP : True
html : False


**Q4. Consider the below student_id array:**

**Q4-1:** Reverse the **student_id** array. Print both original and reversed array.

**Q4-2:** Get the 3-largest values of **student_id** array.

In [211]:
import numpy as np
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])

In [214]:
# Type your solution here
# Q4-1
reversed_student_id = np.flip(student_id) # flips array and places it into a new variable
print(student_id)
print(reversed_student_id)

[1023 5202 6230 1671 1682 5241 4532]
[4532 5241 1682 1671 6230 5202 1023]


In [215]:
# Q4-2
sorted_values = np.sort(student_id)      # sorts the array in ascending order
largest_values = sorted_values[4:]       # gets 3 last values from sorted array (the largest)
print(largest_values)

[5202 5241 6230]


# **Q5: Write a numpy program to print sum of all the multiples of 3 or 5 below 100**

In [216]:
# Type your solution here
# Hint: you can use arange to start off
import numpy as np
totalNumbers = np.arange(1,100,1)                                                       # gets total (100) array of numbers
multOfThreeAndFive = totalNumbers[(totalNumbers % 3 == 0) | (totalNumbers % 5 == 0)]    # finds multiples of 3 or 5
totalSum = np.sum(multOfThreeAndFive)                                                   # adds these values
print(totalSum)

2318


**Q6. Consider the below array.**

Q6.1. Write a code to swap column 1 with column 2.

Q6.2. Write a code to swap row 0 with row 1.

In [217]:
import numpy as np
arr = np.arange(12).reshape(3,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [220]:
# Type your solution here
# Q6-1
arr = np.arange(12).reshape(3,4)
print("Original:")
print(arr)
arr[:,[2,1]] = arr[:,[1,2]]   # switches columns 1 and 2
print("Swapped columns:")
print(arr)

Original:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Swapped columns:
[[ 0  2  1  3]
 [ 4  6  5  7]
 [ 8 10  9 11]]


In [221]:
#Q6-2
arr = np.arange(12).reshape(3,4)
print("Original:")
print(arr)
arr[[1,0]] = arr[[0,1]]    # switches rows 0 and 1
print("Swapped rows:")
print(arr)

Original:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Swapped rows:
[[ 4  5  6  7]
 [ 0  1  2  3]
 [ 8  9 10 11]]
